### ISSUE TITLE
being able to use kubesec with "non secret" files in YAML stream file

### ISSUE THREAD

**Issue by davinkevin** [shyiko/kubesec#30]
Hi, 

It could be simpler to use to be able to run `kubesec` commands on multi "stream" yaml, even if doesn't contain only secrets.

For example, the file `all.yaml`:
```yaml
apiVersion: v1
data:
  application.yaml: |2

    podcastserver:
      rootfolder: /podcasts
      concurrent-download: 40
      max-update-parallels: 256
      number-of-day-to-download: 30
      number-of-day-to-save-cover: 30

    spring:
      datasource.url: jdbc:h2:tcp://database:1521/podcast-server
      jpa.hibernate.ddl-auto: none
kind: ConfigMap
metadata:
  name: podcast-server-d989t5tgb4
  namespace: podcast-server
---
apiVersion: v1
data:
  api.youtube: ofajoeaijeoijeaoaeijeofiajaef
kind: Secret
metadata:
  name: podcast-server-b5cddm29mt
  namespace: podcast-server
type: Opaque
```

I would like to be able to run something like this : 

```shell
$ cat all.yaml | kubesec -d - | kubectl apply -f -
```

But, right now, I have the following result: 

![image](https://user-images.githubusercontent.com/1970922/63628584-8fbe5200-c60d-11e9-8ef3-5698b67e53f2.png)
