### ISSUE TITLE
Helm plugin

### ISSUE THREAD

**Issue by shyiko** [shyiko/kubesec#4]

**Comment by max-rocket-internet** [comment]
Does this mean you are wanting helm to be able to run kubesec and decrypt the data before using it in the chart?

**Comment by shyiko** [comment]
Yep.

**Comment by max-rocket-internet** [comment]
Cool!

I am also looking for a tool to integrate with helm. One such tool is [helm-secrets](https://github.com/futuresimple/helm-secrets), I haven't used it though. Would you be aiming for some different functionality?

**Comment by shyiko** [comment]
[futuresimple/helm-secrets](https://github.com/futuresimple/helm-secrets) looks interesting but not quite what I have in mind. 
1. helm-secrets [appears to use sops for secret .Values management](https://github.com/futuresimple/helm-secrets#using-secret-values-in-helm-chart-secrets-template). Secret templates and values are kept separately. This is different from kubesec, where each Secret is normally "self-sufficient". 

	NOTE: Secret's metadata is not included in MAC and so kubesec-encrypted Secret *can* have template placeholders as shown below:

	```yaml
	apiVersion: v1
	kind: Secret
	metadata:
	  name: helloworld
	  labels:
	    app: helloworld
	    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
	    release: "{{ .Release.Name }}"
	    heritage: "{{ .Release.Service }}"
	type: Opaque
	data:
	  KEY: TUFkWD1iuKs=.O....D...=
	  ANOTHER_KEY: iOy1nf90+M6FrrEIoymN6cOSUYM=.E...=.q...=
	# kubesec:v:3
	# ...
	# kubesec:mac:G5phaA8VV84refpV.idjQQUHj3LS0NJXFZFaCeQ==
	```
	
	You can either "kubesec decrypt, then replace placeholders with values" or "replace placeholders with values, then decrypt". The order doesn't matter. 
For example, [kubetpl](https://github.com/shyiko/kubetpl) can [freeze](https://github.com/shyiko/kubetpl#configmapsecret-freezing) kubesec-managed Secrets before or after decryption.

2. helm plugin for kubesec does not need to concern itself with anything but decryption (kubesec cli provides "edit", "encrypt", etc. already)
